# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

services:
  postgres_app:
    container_name: bank_rest_postgres_app
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_rest
      PGDATA: /data/postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped


#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.
