services:
  postgres_app:
    container_name: bank_rest_postgres_app
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_rest
      PGDATA: /data/postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
